language: java
cache:
  npm: true
  directories:
    - .autoconf
    - $HOME/.m2
sudo: false
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn validate clean install | egrep -v "(^\[INFO\]|^\[DEBUG\])"
after_success:
  - bash <(curl -s https://codecov.io/bash)